LEVEL=../..

TOOLNAME = kensho

USEDLIBS = kensho

LINK_COMPONENTS := support system core

include $(LEVEL)/Makefile.common

CXXFLAGS += -fexceptions
CXXFLAGS += -I/usr/local/include
LDFLAGS += -L/usr/local/lib -lantlr3c